baseurl: /site

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Anton"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
