baseurl: /site

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Anton"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
